spring:
  application:
    name: "gateway"
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      fail-fast: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: ["env", "refresh","health","httptrace","info", "info", "metrics", "prometheus"]