spring:
  application:
    name: "gateway"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kim1387/-spring-cloud-config
      fail-fast: false

ribbon:
  ReadTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: ["env", "refresh"]