version: '3'
##################################################
# healthcheck 안에 있는 주소는 자신의 주소로 바꿔야 함 #
##################################################
services:
  mysql:
    image: qpdh1924/mysql
    container_name: mysql-db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "dkdltm123"
    ports:
      - 3306:3306
    networks:
      msa-network:
          ipv4_address : 172.18.0.2
    volumes:
      - "./init:/docker-entrypoint-initdb.d/"
    # 30 초마다 웹 서버가 10초 이내에
    # 기본 페이지를 제공하는 확인
    # 실패시 3번 재시도 함
    #
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://192.168.0.3:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  config:
    image: qpdh1924/config-server
    depends_on:
      - mysql
    restart: on-failure
    environment:
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "dkdltm123"
    ports:
      - 9888:8888
    networks:
      msa-network:
        ipv4_address : 172.18.0.3
    # 30 초마다 웹 서버가 10초 이내에
    # 기본 페이지를 제공하는 확인
    # 실패시 3번 재시도 함
    #
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://192.168.0.3:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  registry:
    image: qpdh1924/registry
    depends_on:
      - config
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
    ports:
      - 9761:8761
    networks:
      msa-network:
        ipv4_address : 172.18.0.4
    # 30 초마다 웹 서버가 10초 이내에
    # 기본 페이지를 제공하는 확인
    # 실패시 3번 재시도 함
    #
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://192.168.0.3:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  gateway:
    image: qpdh1924/gateway
    depends_on:
      - config
      - registry
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "dkdltm123"
    ports:
      - 8080:8080
    networks:
      msa-network:
        ipv4_address : 172.18.0.5
    # 30 초마다 웹 서버가 10초 이내에
    # 기본 페이지를 제공하는 확인
    # 실패시 3번 재시도 함
    #
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://192.168.0.3:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  auth:
    image: qpdh1924/auth
    depends_on:
      - config
      - registry
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "dkdltm123"
      JWT_SECRET_KEY: "geunyoung_jwt_secret"
    ports:
      - 8081:8080
    networks:
      msa-network:
        ipv4_address : 172.18.0.6
    # 30 초마다 웹 서버가 10초 이내에
    # 기본 페이지를 제공하는 확인
    # 실패시 3번 재시도 함
    #
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://192.168.0.3:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  diet:
    image: qpdh1924/diet
    depends_on:
      - config
      - registry
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "dkdltm123"
    ports:
      - 8082:8080
    networks:
      msa-network:
        ipv4_address : 172.18.0.7
    # 30 초마다 웹 서버가 10초 이내에
    # 기본 페이지를 제공하는 확인
    # 실패시 3번 재시도 함
    #
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://192.168.0.3:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  exercise:
    image: qpdh1924/exercise
    depends_on:
      - config
      - registry
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "dkdltm123"
    ports:
      - 8083:8080
    networks:
      msa-network:
        ipv4_address : 172.18.0.8
    # 30 초마다 웹 서버가 10초 이내에
    # 기본 페이지를 제공하는 확인
    # 실패시 3번 재시도 함
    #
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://192.168.0.3:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  statistics:
    image: qpdh1924/statistics
    depends_on:
      - config
      - registry
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "dkdltm123"
    ports:
      - 8084:8080
    networks:
      msa-network:
        ipv4_address : 172.18.0.9
    # 30 초마다 웹 서버가 10초 이내에
    # 기본 페이지를 제공하는 확인
    # 실패시 3번 재시도 함
    #
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://192.168.0.3:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  msa-network:
    external: true