spring:
  application:
    name: "statistics"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kim1387/-spring-cloud-config
      fail-fast: true
eureka:
  client:
    serviceUrl:
      defaultZone: "http://registry:8761/eureka"
    healthcheck:
      enabled: true
server:
  port: 0
management:
  endpoints:
    web:
      exposure:
        include: ["env", "refresh"]