server:
  port: 8761
spring:
  application:
    name: "discovery-server"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kim1387/-spring-cloud-config
      fail-fast: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
